# Author: Janusz Lewandowski <lew21@xtreeme.org>
# Contributor: David McFarland <corngood@gmail.com>
# Maintainer: Andrew Shark <ashark @at@ linuxcomp.ru>
# Autogenerated from AMD's Packages file

#major=1.4.1
#minor=1

pkgbase=regolith-de
pkgname=(regolith-i3 # (regolith-i3-gaps regolith-i3-gaps-session i3-gaps-wm i3-gaps-wm-dbg i3-snapshot i3xrocks gnome-flashback ubiquity-slideshow-regolith)
#         i3-config-regolith # put it with regolith-i3
         regolith-i3xrocks # allll the i3xrocks shit
	 regolith-styles # alll the styles shit
	 regolith-desktop # regolith-ftue
	 regolith-st 
	 

)
pkgver=1.4.1
pkgrel=1
arch=('x86_64')
url=https://www.amd.com/en/support/kb/release-notes/rn-rad-lin-20-10-unified
license=('custom: multiple')
groups=('regolith-de')
makedepends=('wget')

#DLAGENTS='https::/usr/bin/wget --referer https://www.amd.com/en/support/kb/release-notes/rn-rad-lin-20-10-early-preview -N %u'

source=(https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/ayu-theme_0.2.0-1ubuntu1~ppa1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/cahuella_1.0.2-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3-snapshot_1.0-1ubuntu1~ppa1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks_1.3.2_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/nordic_1.6.5-1ubuntu1ppa1_all.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/plymouth-theme-regolith_1.0.0-1_all.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-compositor-compton-glx_1.0.6_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/unstable/+files/regolith-default-settings_1.0.1-1focal1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-desktop_2.63-1focal1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-ftue_1.0.10-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-gdm3-theme_2.0.0-1ubuntu1~ppa1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-gnome-flashback_2.4.14-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-i3-gaps-config_2.4.13-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-lightdm-config_1.0.6-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-look-ayu_2.4.22-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-look-ayu-dark_2.4.22-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-look-ayu-mirage_2.4.22-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-look-cahuella_2.4.22-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-look-lascaille_2.4.22-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-look-nord_2.4.22-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-look-solarized-dark_2.4.22-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-look-ubuntu_2.4.22-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-rofication_1.2.2-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-rofi-config_1.2.5-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-st_0.8.2-1ubuntu20ppa5_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-styles_2.4.22-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-system_1.4.0.3-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/solarc-theme_800c997-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/ubiquity-slideshow-regolith_138.5-ubuntu1~regolith1_all.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/xrescat_1.1-1ubuntu1ppa1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-battery_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-cpu-usage_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-focused-window-name_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-keyboard-layout_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-key-indicator_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-media-player_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-memory_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-net-traffic_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-nm-vpn_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-openvpn_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-temp_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-time_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-volume_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-weather_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/i3xrocks-wifi_3.0.21-1_amd64.deb
	https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/regolith-i3xrocks-config_3.0.21-1_amd64.deb
	http://archive.ubuntu.com/ubuntu/pool/main/g/gnome-session/gnome-session-bin_3.36.0-2ubuntu1_amd64.deb
	http://archive.ubuntu.com/ubuntu/pool/main/g/gnome-session/gnome-session-common_3.36.0-2ubuntu1_all.deb


)
sha256sums=('SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
	    'SKIP'
	    'SKIP'

)

PKGEXT=".pkg.tar"


# extracts a debian package
# $1: deb file to extract
extract_deb() {
    local tmpdir="$(basename "${1%.deb}")"
    rm -Rf "$tmpdir"
    mkdir "$tmpdir"
    cd "$tmpdir"
    ar x "$1"
    tar -C "${pkgdir}" -xf data.tar.xz
}
# move ubuntu specific /usr/lib/x86_64-linux-gnu to /usr/lib
# $1: debian package library dir (goes from opt/amdgpu or opt/amdgpu-pro and from x86_64 or i386)
# $2: arch package library dir (goes to usr/lib or usr/lib32)
move_libdir() {
    local deb_libdir="$1"
    local arch_libdir="$2"

    if [ -d "${pkgdir}/${deb_libdir}" ]; then
        if [ ! -d "${pkgdir}/${arch_libdir}" ]; then
            mkdir -p "${pkgdir}/${arch_libdir}"
        fi
        mv -t "${pkgdir}/${arch_libdir}/" "${pkgdir}/${deb_libdir}"/*
        find ${pkgdir} -type d -empty -delete
    fi
}
# move copyright file to proper place and remove debian changelog
move_copyright() {
    find ${pkgdir}/usr/share/doc -name "changelog.Debian.gz" -delete
    mkdir -p ${pkgdir}/usr/share/licenses/${pkgname}
    find ${pkgdir}/usr/share/doc -name "copyright" -exec mv {} ${pkgdir}/usr/share/licenses/${pkgname} \;
    find ${pkgdir}/usr/share/doc -type d -empty -delete
}

package_regolith-i3 () {
    pkgdesc="Regolith's i3-gaps"
    license=('MIT')
#    install=amdgpu-core-meta.install
    arch=('x86_64')
    depends=('i3-gaps' 'i3-status' 'xorg' 'xorg-apps' 'python-i3ipc' 'gnome-flashback' 
             'accountsservice' 'cups-pk-helper' 'libgtop' 'gnome-control-center' 'gnome-desktop' 
	     'gnome-settings-daemon' 'playerctl')
    optdepends=('picom: For compositing/desktop effects (strongly recommended!'
		'unclutter-xfixes-git: For unclutter')
    provides=('i3-wm' 'i3-snapshot' 'i3-gnome-flashback' 'gnome-session' 'gnome-session-bin'
	      'gnome-session-common')
    conflicts=('i3-wm' 'i3-gaps' 'i3-gaps-git' 'i3-gaps-rounded-git' 'i3-gaps-next-git'
               'i3-gnome-flashback' 'gnome-session')

    extract_deb "${srcdir}"/i3-snapshot_1.0-1ubuntu1~ppa1_amd64.deb
    extract_deb "${srcdir}"/regolith-gnome-flashback_2.4.14-1_amd64.deb
    extract_deb "${srcdir}"/xrescat_1.1-1ubuntu1ppa1_amd64.deb
    extract_deb "${srcdir}"/gnome-session-bin_3.36.0-2ubuntu1_amd64.deb
    extract_deb "${srcdir}"/gnome-session-common_3.36.0-2ubuntu1_all.deb


    move_copyright
}

package_regolith-i3xrocks () {
    pkgdesc="Regolith's i3xrocks with associated widgets and config files"
    license=('GPLv3')
    arch=('x86_64')
    depends=('glibc' 'accountsservice')
    conflicts=('i3xrocks' 'i3blocks')
    provides=('i3xrocks' 'i3blocks')

    extract_deb "${srcdir}"/i3xrocks_1.3.2_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-battery_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-cpu-usage_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-focused-window-name_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-keyboard-layout_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-key-indicator_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-media-player_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-memory_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-net-traffic_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-nm-vpn_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-openvpn_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-temp_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-time_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-volume_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-weather_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/i3xrocks-wifi_3.0.21-1_amd64.deb

    move_copyright
}


package_regolith-styles () {
    pkgdesc="Regolith's themes for i3, gdm, gtk, rofi, plymouth, etc."
    license=('custom: FIXME')
# FIXME    depends=("rofi" "regolith-i3" "gdm" "gtk3")

    extract_deb "${srcdir}"/ayu-theme_0.2.0-1ubuntu1~ppa1_amd64.deb
    extract_deb "${srcdir}"/cahuella_1.0.2-1_amd64.deb
    extract_deb "${srcdir}"/nordic_1.6.5-1ubuntu1ppa1_all.deb
    extract_deb "${srcdir}"/plymouth-theme-regolith_1.0.0-1_all.deb
    extract_deb "${srcdir}"/regolith-gdm3-theme_2.0.0-1ubuntu1~ppa1_amd64.deb
    extract_deb "${srcdir}"/regolith-look-ayu_2.4.22-1_amd64.deb
    extract_deb "${srcdir}"/regolith-look-ayu-dark_2.4.22-1_amd64.deb
    extract_deb "${srcdir}"/regolith-look-ayu-mirage_2.4.22-1_amd64.deb
    extract_deb "${srcdir}"/regolith-look-cahuella_2.4.22-1_amd64.deb
    extract_deb "${srcdir}"/regolith-look-lascaille_2.4.22-1_amd64.deb
    extract_deb "${srcdir}"/regolith-look-nord_2.4.22-1_amd64.deb
    extract_deb "${srcdir}"/regolith-look-solarized-dark_2.4.22-1_amd64.deb
    extract_deb "${srcdir}"/regolith-look-ubuntu_2.4.22-1_amd64.deb
    extract_deb "${srcdir}"/regolith-styles_2.4.22-1_amd64.deb
    extract_deb "${srcdir}"/solarc-theme_800c997-1_amd64.deb

    move_copyright
}

package_regolith-desktop-config () {
    pkgdesc="Regolith DE's desktop settings and configuration files, for rofi, i3, lightdm, i3xrocks, etc. plus ubiquity-slideshow-regolith"
    license=('custom: FIXME')
    provides=('regolith-ftue' 'regolith-rofication')
    depends=('rofi')
    optdepends=('lightdm: For the Regolith LightDM customization' 
		'regolith-i3xrocks: For i3xrocks (i3blocks) support'
	        'i3-gaps: For i3-gaps config support'
		'picom: For compositing configuration')

    extract_deb "${srcdir}"/regolith-compositor-compton-glx_1.0.6_amd64.deb
    extract_deb "${srcdir}"/regolith-default-settings_1.0.1-1focal1_amd64.deb
    extract_deb "${srcdir}"/regolith-desktop_2.63-1focal1_amd64.deb
    extract_deb "${srcdir}"/regolith-ftue_1.0.10-1_amd64.deb
    extract_deb "${srcdir}"/regolith-lightdm-config_1.0.6-1_amd64.deb
    extract_deb "${srcdir}"/regolith-i3-gaps-config_2.4.13-1_amd64.deb
    extract_deb "${srcdir}"/regolith-rofi-config_1.2.5-1_amd64.deb
    extract_deb "${srcdir}"/regolith-system_1.4.0.3-1_amd64.deb
    extract_deb "${srcdir}"/ubiquity-slideshow-regolith_138.5-ubuntu1~regolith1_all.deb
    extract_deb "${srcdir}"/regolith-i3xrocks-config_3.0.21-1_amd64.deb
    extract_deb "${srcdir}"/regolith-rofication_1.2.2-1_amd64.deb    
    move_copyright
## extra commands
    mv "${pkgdir}"/usr/lib/python3 "${pkgdir}"/usr/lib/python3.8
    mv "${pkgdir}"/usr/lib/python3.8/dist-packages "${pkgdir}"/usr/lib/python3.8/site-packages
    rm "${pkgdir}"/usr/share/backgrounds/lucas-bellator-C0OD8OM-oM0-unsplash.jpg
    rm "${pkgdir}"/usr/share/applications/reboot.desktop
    rm "${pkgdir}"/usr/share/applications/logout.desktop
    rm "${pkgdir}"/usr/share/applications/shutdown.desktop


}


package_regolith-st () {
	pkgdesc="Regolith's fork of st - the simple terminal"
	license=("custom: FIXME")
	provides=('st')
	conflicts=('st')

	extract_deb "${srcdir}"/regolith-st_0.8.2-1ubuntu20ppa5_amd64.deb

}